app:
  name: "discovery"

spring:
  application:
    name: ${app.name}
  main:
    banner-mode: "off"

eureka:
  instance:
    instanceId: ${app.name}-${random.value}
  client:
    registerWithEureka: false
    fetchRegistry: false