title: Spring Boot Microservice
description: A look at the microservice architecture
theme: jekyll-theme-slate

collections_dir: collections
collections:
  repo_projects:
    output: true
  posts:
  getting-started:
    output: true
    
repo:
  raw-url: https://raw.githubusercontent.com/nosliwmichael/spring-boot-microservice/
  branch: master