server:
  port: 8080

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/discovery-service/eureka/

logging:
  level:
    com:
      netflix:
        eureka: OFF
        discovery: OFF